const level1 = new Level(
  [
    new JellyfishYellow(),
    new JellyfishYellow(),
    new JellyfishYellow(),
    new JellyfishYellow(),
    new JellyfishYellow(),
    new JellyfishLila(),
    new JellyfishLila(),
    new JellyfishLila(),
    new JellyfishLila(),
    new JellyfishLila(),
  ],
  [new PufferfishRed(), new PufferfishGreen(), new PufferfishOrange()],
  [new Light()],
  [
    new Bottle(500),
    new Bottle(700),
    new Bottle(1000),
    new Bottle(1200),
    new Bottle(1700),
    new Bottle(1900),
  ],
  [
    new Coin(500),
    new Coin(550),
    new Coin(700),
    new Coin(800),
    new Coin(1000),
    new Coin(1100),
    new Coin(1150),
    new Coin(1340),
    new Coin(1380),
    new Coin(1450),
    new Coin(1500),
    new Coin(1600),
    new Coin(1650),
    new Coin(1700),
    new Coin(1720),
  ],
  [
    new BackgroundObject("img/3. Background/Layers/5. Water/L1.png", -719),
    new BackgroundObject("img/3. Background/Layers/4.Fondo 2/L2.png", -719),
    new BackgroundObject("img/3. Background/Layers/3.Fondo 1/L2.png", -719),
    new BackgroundObject("img/3. Background/Layers/2. Floor/L2.png", -719),

    new BackgroundObject("img/3. Background/Layers/5. Water/L1.png", 0),
    new BackgroundObject("img/3. Background/Layers/4.Fondo 2/L1.png", 0),
    new BackgroundObject("img/3. Background/Layers/3.Fondo 1/L1.png", 0),
    new BackgroundObject("img/3. Background/Layers/2. Floor/L1.png", 0),

    new BackgroundObject("img/3. Background/Layers/5. Water/L1.png", 719),
    new BackgroundObject("img/3. Background/Layers/4.Fondo 2/L2.png", 719),
    new BackgroundObject("img/3. Background/Layers/3.Fondo 1/L2.png", 719),
    new BackgroundObject("img/3. Background/Layers/2. Floor/L2.png", 719),

    new BackgroundObject("img/3. Background/Layers/5. Water/L1.png", 719 * 2),
    new BackgroundObject("img/3. Background/Layers/4.Fondo 2/L1.png", 719 * 2),
    new BackgroundObject("img/3. Background/Layers/3.Fondo 1/L1.png", 719 * 2),
    new BackgroundObject("img/3. Background/Layers/2. Floor/L1.png", 719 * 2),

    new BackgroundObject("img/3. Background/Layers/5. Water/L1.png", 719 * 3),
    new BackgroundObject("img/3. Background/Layers/4.Fondo 2/L2.png", 719 * 3),
    new BackgroundObject("img/3. Background/Layers/3.Fondo 1/L2.png", 719 * 3),
    new BackgroundObject("img/3. Background/Layers/2. Floor/L2.png", 719 * 3),
  ]
);
